# Configuration file for SNP Analysis Pipeline v2.1

# Paths to tools and directories
paths:
  bwa_base_path: "/usr/local/bin/bwa/"  # Base path for BWA
  bowtie_base_path: "/usr/local/bin/bowtie/"  # Base path for Bowtie2
  fastp_path: "/usr/bin/fastp"  # Path to fastp for trimming
  log_file: "pipeline.log"  # Path to the log file
  output_dir: "output"  # Directory for pipeline output files

# Threads and performance settings
threads: 4  # Number of threads to use for parallel tasks
max_log_size: 5242880  # Maximum log file size in bytes (5MB)
backup_count: 3  # Number of backup log files to keep

# Chromosomes to analyze
chromosomes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, "X", "Y"]

# Reference genome settings
reference_genome:
  hg38:
    bwa_index: "/usr/local/bin/bwa/hg38/GRCh38_reference.fa"  # Path to BWA index for hg38
    bowtie_index: "/usr/local/bin/bowtie/hg38/bowtie"  # Path to Bowtie2 index for hg38

# SRA tools settings
sra_tools:
  prefetch_path: "prefetch"  # Path to prefetch (default: assume it's in PATH)
  fasterq_dump_path: "fasterq-dump"  # Path to fasterq-dump (default: assume it's in PATH)

# fastp settings
fastp:
  threads: 4  # Number of threads for fastp
  html_report: "fastp.html"  # Path to save fastp HTML report
  json_report: "fastp.json"  # Path to save fastp JSON report

# VCF generation settings
vcf:
  bcftools_path: "bcftools"  # Path to bcftools (default: assume it's in PATH)
  vcfutils_path: "vcfutils.pl"  # Path to vcfutils.pl (default: assume it's in PATH)